# **My First ML Project**

## **Loading Data**

In [3]:
from google.colab import files
import pandas as pd
import io
print("select the dataset to upload")
uploaded = files.upload()
for filename, content in uploaded.items():
  df = pd.read_excel(io.BytesIO(content))
  print(df)

select the dataset to upload

Saving fifa_world_cup_2026_player_performance.xlsx to fifa_world_cup_2026_player_performance.xlsx
      player_id       player_name  age nationality   team  jersey_number  \
0        P00055        Rodri Fati   26     Spanish  Spain              3
1        P00070   Ansu Le Normand   19     Spanish  Spain             18
2        P00066        Gavi Ramos   18     Spanish  Spain             14
3        P00073     Pedro Cubarsi   20     Spanish  Spain             21
4        P00059  Alvaro Oyarzabal   23     Spanish  Spain              7
...         ...               ...  ...         ...    ...            ...
54595    P00996       Amir Younis   28       Iraqi   Iraq              8
54596    P01006  Safaa Al-Khafaji   20       Iraqi   Iraq             18
54597    P01008     Ahmed Hussein   26       Iraqi   Iraq             20
54598    P00991     Ibrahim Mhawi   30       Iraqi   Iraq              3
54599    P00989  Mohannad Hussein   27       Iraqi   Iraq              1

         position  height_cm  weight_kg preferred_foot  ... possession_impact  \
0      Goalkeeper        195         75           Left  ...               1.1
1      Midfielder        178         75          Right  ...               3.5
2      Midfielder        177         72           Left  ...              15.3
3         Forward        182         74          Right  ...               1.2
4        Defender        191         81           Left  ...               6.2
...           ...        ...        ...            ...  ...               ...
54595    Defender        177         73          Right  ...               0.0
54596  Midfielder        176         72          Right  ...               0.0
54597  Midfielder        173         77           Left  ...               0.0
54598  Goalkeeper        190         81          Right  ...               0.0
54599  Goalkeeper        187         73          Right  ...               0.0

       pressure_resistance creativity_score  consistency_score  \
0                     44.2             55.9               42.0
1                     38.2             43.7               31.1
2                     99.0             99.0               83.4
3                     19.8             42.3               40.9
4                     44.1             33.5               60.0
...                    ...              ...                ...
54595                 41.9             27.7               31.3
54596                 64.2             53.1               64.8
54597                 75.4             55.0               65.0
54598                 96.3             39.6               99.0
54599                 99.0             34.1               99.0

      clutch_performance_score total_goals_tournament  \
0                         51.8                      0
1                         52.7                      0
2                         54.8                      1
3                         78.5                      5
4                         56.6                      0
...                        ...                    ...
54595                     40.5                      1
54596                     64.3                      2
54597                     64.5                      1
54598                     99.0                      0
54599                     99.0                      0

      total_assists_tournament total_minutes_tournament  \
0                            0                      242
1                            3                      342
2                            1                      245
3                            3                      422
4                            0                      440
...                        ...                      ...
54595                        0                       97
54596                        0                      206
54597                        1                      359
54598                        0                      342
54599                        0                      286

      player_of_match_awards  tournament_rating
0                          0                5.8
1                          0                5.5
2                          0                8.4
3                          0                6.7
4                          0                5.7
...                      ...                ...
54595                      0                0.0
54596                      0                0.0
54597                      0                0.0
54598                      0                0.0
54599                      0                0.0

[54600 rows x 75 columns]

# **Data Cleaning**

## **checking the data**

In [10]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  int64
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(44), object(13)
memory usage: 31.2+ MB

### **Removing Duplicates**

In [8]:
df.drop_duplicates()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

## **fixing country names**

In [15]:
df['nationality'] = df["nationality"].replace('spanish','spain')
df['nationality'] = df["nationality"].replace('american','usa')
df['nationality'] = df["nationality"].replace('Iraqi','Iraq')
df['nationality'].unique()
df['nationality'].value_counts()

nationality
Qatari           1716
Jamaican         1534
Moroccan         1430
Dutch            1404
Italian          1378
Saudi            1352
Belgian          1326
Turkish          1300
Croatian         1274
Scottish         1274
Peruvian         1248
Canadian         1248
Ecuadorian       1222
Panamanian       1222
Australian       1222
Tunisian         1222
Colombian        1196
Costa Rican      1196
Ghanaian         1170
Spanish          1170
Uruguayan        1170
Egyptian         1170
Brazilian        1170
Cameroonian      1144
English          1144
Uzbek            1144
Portuguese       1118
Danish           1118
Serbian          1092
Algerian         1066
Iraq             1066
Nigerian         1040
Mexican          1040
Polish           1014
Ukrainian         988
Senegalese        988
American          988
Iranian           988
Chilean           962
Swedish           936
Japanese          936
South African     910
Swiss             910
French            884
South Korean      884
Argentine         884
German            884
Austrian          858
Name: count, dtype: int64

# **Simple Analysis**

### **1. Columns**

In [4]:
df.columns

Index(['player_id', 'player_name', 'age', 'nationality', 'team',
       'jersey_number', 'position', 'height_cm', 'weight_kg', 'preferred_foot',
       'club_name', 'market_value_eur', 'match_id', 'match_date', 'stadium',
       'city', 'opponent_team', 'tournament_stage', 'match_result',
       'goals_team', 'goals_opponent', 'minutes_played', 'goals', 'assists',
       'shots', 'shots_on_target', 'expected_goals_xg', 'expected_assists_xa',
       'key_passes', 'successful_passes', 'total_passes', 'pass_accuracy',
       'dribbles_attempted', 'successful_dribbles', 'crosses',
       'successful_crosses', 'tackles', 'interceptions', 'clearances',
       'blocks', 'aerial_duels_won', 'aerial_duels_lost', 'recoveries',
       'defensive_actions', 'fouls_committed', 'fouls_suffered',
       'yellow_cards', 'red_cards', 'offsides', 'saves', 'save_percentage',
       'punches', 'clean_sheet', 'goals_conceded', 'penalty_saves',
       'distance_covered_km', 'sprint_distance_km', 'top_speed_kmh',
       'accelerations', 'decelerations', 'stamina_score', 'player_rating',
       'performance_score', 'offensive_contribution', 'defensive_contribution',
       'possession_impact', 'pressure_resistance', 'creativity_score',
       'consistency_score', 'clutch_performance_score',
       'total_goals_tournament', 'total_assists_tournament',
       'total_minutes_tournament', 'player_of_match_awards',
       'tournament_rating'],
      dtype='object')

## **checking the data**

In [5]:
df.head()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

## **finding the best players**

In [13]:
df.nlargest(10,'creativity_score')[["player_name","nationality","team","creativity_score"]]

            player_name nationality         team  creativity_score
2            Gavi Ramos     Spanish        Spain              99.0
10       Ferran Cubarsi     Spanish        Spain              99.0
96            Cody Lang       Dutch  Netherlands              99.0
101         Frenkie Ake       Dutch  Netherlands              99.0
148           Pape Sarr  Senegalese      Senegal              99.0
172     Ramiz Boufantin    Algerian      Algeria              99.0
177     Houssem Brahimi    Algerian      Algeria              99.0
209  Richarlison Junior   Brazilian       Brazil              99.0
231      Vinicius Nunes   Brazilian       Brazil              99.0
236        Cody de Jong       Dutch  Netherlands              99.0

# **basic data overveiw**

In [14]:
print ('shape:',df.shape)
print('\ncolumns:',df.columns.tolist())
df.isnull().sum()

shape: (54600, 75)

columns: ['player_id', 'player_name', 'age', 'nationality', 'team', 'jersey_number', 'position', 'height_cm', 'weight_kg', 'preferred_foot', 'club_name', 'market_value_eur', 'match_id', 'match_date', 'stadium', 'city', 'opponent_team', 'tournament_stage', 'match_result', 'goals_team', 'goals_opponent', 'minutes_played', 'goals', 'assists', 'shots', 'shots_on_target', 'expected_goals_xg', 'expected_assists_xa', 'key_passes', 'successful_passes', 'total_passes', 'pass_accuracy', 'dribbles_attempted', 'successful_dribbles', 'crosses', 'successful_crosses', 'tackles', 'interceptions', 'clearances', 'blocks', 'aerial_duels_won', 'aerial_duels_lost', 'recoveries', 'defensive_actions', 'fouls_committed', 'fouls_suffered', 'yellow_cards', 'red_cards', 'offsides', 'saves', 'save_percentage', 'punches', 'clean_sheet', 'goals_conceded', 'penalty_saves', 'distance_covered_km', 'sprint_distance_km', 'top_speed_kmh', 'accelerations', 'decelerations', 'stamina_score', 'player_rating', 'performance_score', 'offensive_contribution', 'defensive_contribution', 'possession_impact', 'pressure_resistance', 'creativity_score', 'consistency_score', 'clutch_performance_score', 'total_goals_tournament', 'total_assists_tournament', 'total_minutes_tournament', 'player_of_match_awards', 'tournament_rating']

player_id                   0
player_name                 0
age                         0
nationality                 0
team                        0
                           ..
total_goals_tournament      0
total_assists_tournament    0
total_minutes_tournament    0
player_of_match_awards      0
tournament_rating           0
Length: 75, dtype: int64

# **feature engineering**

***overall performance score***

In [20]:
df['overall_score']=(df['creativity_score']+df['possession_impact']+df['pressure_resistance']+df['consistency_score'])/4
print('new features created')

new features created

In [22]:
df.to_csv('fifa_cleaned _with _features.csv',index=False, sep=',')
files.download('fifa_cleaned _with _features.csv')

In [23]:
df=pd.read_csv('fifa_cleaned _with _features.csv')
df.head()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating,overall_score
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,44.2,55.9,42.0,51.8,0,0,242,0,5.8,35.800
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,38.2,43.7,31.1,52.7,0,3,342,0,5.5,29.125
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,99.0,99.0,83.4,54.8,1,1,245,0,8.4,74.175
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,19.8,42.3,40.9,78.5,5,3,422,0,6.7,26.050
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,44.1,33.5,60.0,56.6,0,0,440,0,5.7,35.950